name: testing push and pr event
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "triggered by push to ${{github.ref_name}}"
